//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Region
{
    public int RegionID { get; set; }
    public string RegionName { get; set; }
    public int CompanyID { get; set; }
    public Nullable<System.DateTime> DateCreated { get; set; }
    public Nullable<System.DateTime> DateModified { get; set; }
    public Nullable<int> AreaID { get; set; }
}
